AppLozic/ApplozicSwift

- Sources/Controllers/ALKConversationViewController.swift
- Sources/Controllers/ALKCreateGroupViewController.swift
- Sources/Controllers/ALKSelectParticipantToAddViewController.swift
- Sources/ViewModels/ALKConversationViewModel.swift
- Sources/Views/StoryBoards/CustomCamera.storyboard
- Sources/Views/StoryBoards/CustomPicker.storyboard
> Fix group details functionality

- Sources/Controllers/ALKConversationViewController.swift
- Sources/ViewModels/ALKConversationListViewModel.swift
- Sources/ViewModels/ALKConversationViewModel.swift
Update access control  of classes and methods required to launch individual chat
> [AL-2335] Update access control to launch individual chat

- Demo/ApplozicSwiftDemo.xcodeproj/project.pbxproj
- Demo/ApplozicSwiftDemo/ALChatManager.swift
- Sources/Controllers/ALKBaseViewController.swift
- Sources/Controllers/ALKConversationListViewController.swift
- Sources/Controllers/ALKConversationViewController+TableView.swift
- Sources/Controllers/ALKConversationViewController.swift
- Sources/Utilities/ALKHTTPManager.swift
- Sources/Utilities/NSLayoutConstraint+Extension.swift
- Sources/Utilities/UIView+Extension.swift
- Sources/ViewModels/ALKContextTitleViewModel.swift
- Sources/ViewModels/ALKConversationListViewModel.swift
- Sources/ViewModels/ALKConversationViewModel.swift
- Sources/Views/ALKChatCell.swift
- Sources/Views/ALKContextTitleView.swift
This also changes the access-level of `ALKConversationListViewController` and `ALKConversationViewController`  class to `open`, so that it can be used to subclass.
> [AL-2341] Add context based chat

- ApplozicSwift.podspec
- Demo/Podfile
- Demo/Podfile.lock
> [AL-2417] Update kingfisher to 3.13.1 and Applozic to 4.6.1

- Demo/ApplozicSwiftDemo/Assets.xcassets/AppIcon.appiconset/Contents.json
- Sources/Controllers/ALKConversationViewController+TableView.swift
- Sources/Controllers/ALKConversationViewController.swift
This adds a new background view in the ALKConversationViewController which can be used to add a background image or just a colour update, by subclassing the view controller.
> [AL-2439] Add background view which can be used to add background image

- Sources/Controllers/ALKConversationListViewController.swift
Change access level of delegate methods in ALKConversationListViewController to open
> [AL-2509] Change access level of delegate methods

- .gitignore
- Dangerfile
- Gemfile
- buddybuild_postbuild.sh
This PR adds support for danger.
> [AL-2534] Add Danger #trivial [WIP]

- Sources/Controllers/ALKConversationViewController.swift
- Sources/Controllers/ALKNewChatViewController.swift
- Sources/Views/ALKChatBar.swift
Updates chatbar constraints and passes configuration while initializing ALKCreateGroupViewController.
> [AL-2828]Update chatbar constraints for iphone 5

- CHANGELOG.md
- Dangerfile
- Demo/ApplozicSwiftDemo.xcodeproj/project.pbxproj
- Added CHANGELOG file.
- Added a check for changelog update when the change is nontrivial.
- Added `CS` Jira key to link the issues.
> [AL-2888]Dangerfile: Add release notes check #trivial

- CHANGELOG.md
- Sources/Controllers/ALKCreateGroupViewController.swift
- Sources/Controllers/ALKNewChatViewController.swift
- Sources/Controllers/ALKSelectParticipantToAddViewController.swift
- Sources/ViewModels/ALKNewChatViewModel.swift
* Add support for contacts group in swift using settings of objective c 
* Add configuration in ALKSelectParticipantToAddViewController
> CS-108  Contacts group 📱

- ApplozicSwift.podspec
- Demo/Podfile.lock
Updates Applozic to version 5.11.0
> Pod: Update Applozic #trivial

- ApplozicSwift.podspec
- Demo/Podfile.lock
Updates version to 0.15.0 for the release
> Bump version to 0.15.0 #trivial

- CHANGELOG.md
- Demo/ApplozicSwiftDemo/ALChatManager.swift
- Sources/Controllers/ALKConversationListViewController.swift
- Sources/Utilities/ALKPushNotificationHandler.swift
Fixes [CS-127](https://applozic.atlassian.net/browse/CS-127)
> [CS-127]Use ALPushAssist's topViewController to launch

- ApplozicSwift.podspec
- CHANGELOG.md
- Demo/Podfile.lock
This PR contains the update for pod version and changelog released version.
> Release 0.15.1

- CHANGELOG.md
- Sources/Utilities/Message+Style.swift
- Sources/Views/ALKMessageCell.swift
While sending multiline messages, they are getting trimmed.
Also gap between consecutive messages is uneven.
> [AL-2909] Fix trimming of multiline messages.

- ApplozicSwift.podspec
- CHANGELOG.md
- Demo/Podfile.lock
- Sources/ViewModels/ALKConversationViewModel.swift
- Updated Applozic version to 6.0.0
- Fixed errors after the Applozic update.
- Updated ApplozicSwift's version to 1.0.0
> Release 1.0.0 #trivial

- CHANGELOG.md
- Sources/Controllers/ALKConversationListViewController.swift
- Sources/Controllers/ALKConversationViewController.swift
This PR will fix an issue where chat when opened from push notification, will not scroll to the latest message.
> [AL-2920]Fix message scroll issue when tapped on push notification

- ApplozicSwift.podspec
- Demo/Podfile.lock
- Sources/Controllers/ALKConversationListViewController.swift
This will update the Applozic version to 6.2.0.
> [AL-2927]Update applozic and fix logs error in the new build system #trivial

- Sources/Controllers/ALKConversationListViewController.swift
- Sources/Models/ALKConfiguration.swift
Added a new option in `ALKConfiguration` to hide the start new chat button.
> [AL-2983] Add a config to hide new chat button

- CHANGELOG.md
- Sources/Controllers/ALKConversationViewController.swift
- Sources/Resources/Base.lproj/Localizable.strings
- Sources/Utilities/SystemMessage.swift
- Sources/Views/ALKChatBar.swift
This PR will Update chat screen to enable/disble chat for user when user is added/removed in the group.
> [AL-3004] Update chat to disable/enable sending messages in group

- Sources/Controllers/ALKConversationListViewController.swift
- Sources/Controllers/ALKConversationViewController+TableView.swift
- Sources/Controllers/ALKConversationViewController.swift
- Sources/Controllers/ALKCreateGroupViewController.swift
- Sources/Controllers/ALKCustomCameraViewController.swift
- Sources/Controllers/ALKCustomVideoCaptureController.swift
- Sources/Controllers/ALQuickReplyCollectionViewCell.swift
- Sources/Utilities/ALMessage+Extension.swift
- Sources/Utilities/String+Extension.swift
- Sources/Utilities/UIImage+Extension.swift
- Sources/ViewModels/ALKConversationListViewModel.swift
- Sources/ViewModels/ALKConversationViewModel.swift
- Sources/ViewModels/ALKLocationPreviewViewModel.swift
- Sources/Views/ALKAudioPlayer.swift
- Sources/Views/ALKChatBar.swift
- Sources/Views/ALKChatCell.swift
- Sources/Views/ALKFriendContactCell.swift
- Sources/Views/ALKGenericCardCell.swift
- Sources/Views/ALKGenericListCell.swift
- Sources/Views/ALKMoreBar.swift
- Sources/Views/ALKReplyMessageView.swift
- Sources/Views/ALKTemplateMessageCell.swift
- Sources/Views/ALKTemplateMessagesView.swift
- Sources/Views/KDCircularProgress.swift
This will bring down warnings in ApplozicSwift under 5
> Reduce warnings in ApplozicSwift #trivial

- Sources/Controllers/ALKConversationViewController.swift
Now changing configuration after initializing `ALKChatBar` will update the views that depend on the configuration properties.
> [AL-3130]ChatBar: Fix configuration update issue #trivial

- Sources/Controllers/ALKBaseNavigationController.swift
- Sources/Models/ALKConfiguration.swift
This PR will add a setting to change status bar style which will be used by all the view controllers.
> Add settings to change status bar style in view controllers #trivial

- Demo/ApplozicSwiftDemo.xcodeproj/project.pbxproj
- Demo/Playground/CurvedButton.playground/Contents.swift
- Demo/Playground/CurvedButton.playground/contents.xcplayground
- Demo/Playground/QuickReplyView.playground/Contents.swift
- Demo/Playground/QuickReplyView.playground/contents.xcplayground
This PR is on top of PR #125
It will add playground for demonstrating usage of ALKCurvedButton
> Add playground for curved button and quick reply view #trivial

- Demo/ApplozicSwiftDemo/ALChatManager.swift
- Demo/ApplozicSwiftDemo/LoginViewController.swift
- Sources/Controllers/ALKNewChatViewController.swift
- Sources/ViewModels/ALKNewChatViewModel.swift
This PR will add some methods in ALChatManager which were present in Objective C sdk.
> Add missing methods in ALChatManager #trivial

- CHANGELOG.md
- Demo/ApplozicSwiftDemoTests/Tests/ALMessageTests.swift
- Sources/Controllers/ALKConversationViewController+TableView.swift
- Sources/Controllers/ALKConversationViewController.swift
- Sources/Controllers/WebViewController.swift
- Sources/Models/ALKMessageModel.swift
- Sources/Utilities/ALMessage+Extension.swift
- Sources/Utilities/QuickReplyConfig.swift
- Sources/ViewModels/ALKConversationViewModel.swift
- Sources/Views/ALKCurvedButton.swift
- Sources/Views/ALKFriendQuickReplyCell.swift
- Sources/Views/ALKMessageButtonCell.swift
- Sources/Views/ALKMyQuickReplyCell.swift
- Sources/Views/ButtonsView.swift
This PR is on top of PR #125 
It will add views for submit button and link button.
> [AL-3137] Add Submit and Link buttons

- ApplozicSwift.podspec
- CHANGELOG.md
- Demo/ApplozicSwiftDemo.xcodeproj/project.pbxproj
- Demo/Podfile.lock
- Bumped the version to 2.2.0
- Updated CocoaPods to v1.6.0
- Did some minor changes in the Changelog entries for 2.2.0 release.
> Release 2.2.0 🚀

- README.md
Replaced application key with App ID. Added docs link and removed the docs related to registration and launch.
> Update application key and add docs link

- ApplozicSwift.podspec
- CHANGELOG.md
- Demo/Podfile.lock
Also, Updated Applozic to 6.8.2.
> Release 2.3.0 🚀

- CHANGELOG.md
- Demo/Podfile.lock
- Sources/Utilities/ALMessageArrayWrapper+Extension.swift
- Sources/ViewModels/ALKConversationViewModel.swift
This PR will remove duplicate entry of same message in detailed chat screen.
For open group, same message was coming 4 times.
Tested on simulator. Working fine for open group. Need testing on device.
> [AL-3302] Remove duplicate messages in detailed chat screen

- Sources/Controllers/ALKConversationViewController.swift
- Sources/Models/ALKConfiguration.swift
This PR will fix the issue while sending metadata along with suggested replies. 
Tested on simulator, working fine!
> Fix message metadata issue in sending suggested replies #trivial

- ApplozicSwift.podspec
- CHANGELOG.md
- Demo/Podfile.lock
> Release 2.5.0 🚀

- ApplozicSwift.podspec
- CHANGELOG.md
- Demo/Podfile.lock
> Release 2.5.1 🚀

- CHANGELOG.md
- Sources/Controllers/ALKConversationViewController.swift
- Sources/Controllers/ALKCreateGroupViewController.swift
- Sources/ViewModels/ALKCreateGroupViewModel.swift
This PR will do the following :: 
1. Send a notification when user profile is clicked in navigation bar.
2. Real time updates in group details page.
> Send notification when user name is clicked in navigation title

- ApplozicSwift.podspec
- CHANGELOG.md
- Demo/Podfile.lock
Bumped the version to 2.7.0. Also, updated Applozic to 6.10.0.
> Release 2.7.0 🚀

- CHANGELOG.md
- Sources/Controllers/ALKConversationViewController.swift
- Sources/Controllers/ALKCustomPickerViewController.swift
- Sources/Resources/Base.lproj/Localizable.strings
- Sources/Utilities/ALKActivityIndicator.swift
- Sources/Utilities/SystemMessage.swift
This will fix crash due to force casting indexPath. 
Also, added he checks while exporting video.
> Fix crash when video isn't exported properly

- ApplozicSwift.podspec
- CHANGELOG.md
- Demo/Podfile.lock
Bump pod version to 2.8.0 and update Applozic to 6.12.0
Build was successful locally.
> Release 2.8.0

- ApplozicSwift.podspec
- CHANGELOG.md
- Demo/Podfile.lock
Reverts AppLozic/ApplozicSwift#225
> Revert "Release 2.8.0"

- ApplozicSwift.podspec
- CHANGELOG.md
- Demo/Podfile.lock
- README.md
Updated version to 3.0.0. Also, updated the min. requirements and Applozic version.
> Release 3.0.0 🚀 #trivial

- Sources/Controllers/ALKConversationListViewController.swift
- Sources/Controllers/ALKConversationViewController.swift
Depends on https://github.com/AppLozic/Applozic-iOS-SDK-Dev/pull/679
> Retry connecting to mqtt as long as chat screen is open #trivial

- Demo/ApplozicSwiftDemo/AppDelegate.swift
- Sources/Utilities/ALKPushNotificationHandler.swift
This PR will fix the issue where chat wasn't opening on tap of notification.
> [AL-3573] Fix notification click issue

- ApplozicSwift.podspec
- CHANGELOG.md
- Demo/Podfile.lock
- Sources/Utilities/MGSwipeButton+Extension.swift
- Sources/Utilities/UI+Style.swift
- Sources/Views/ALKChatBar.swift
- Sources/Views/ALKChatCell.swift
- Sources/Views/ALKConversationNavBar.swift
- Sources/Views/ALKFriendGenericCardCell.swift
- Sources/Views/ALKMyGenericCardCell.swift
- Sources/Views/ALKMyQuickReplyCell.swift
- Sources/Views/ALKVoiceCell.swift
- Sources/Views/AudioRecordingView.swift
- Sources/Views/ContactView.swift
This will add full support for RTL languages. 
Tested locally on all the views that we have.
> [AL-3210] Add support for RTL languages

- Sources/Controllers/ALKConversationViewController.swift
- Sources/Models/CardTemplate.swift
- Sources/Utilities/Encodable+Extension.swift
- Sources/Views/ALKGenericCardCell.swift
This PR will fix the following bugs:
1. Suggested reply first button tap action was not working. 
2. Submit button template id 3 tap action was not working.
> Fix issues with rich message actions #trivial

- Sources/Controllers/ALKConversationListViewController.swift
> Delete the unused code

- Sources/Controllers/ALKMediaViewerViewController.swift
Updated image preview constraints and use the safeAreaLayoutGuide
Tried with multiple images of different size, working fine.
> Update image preview constraints

- Demo/ApplozicSwiftDemo.xcworkspace/xcshareddata/xcschemes/ApplozicSwiftDemo.xcscheme
- Demo/ApplozicSwiftDemo.xcworkspace/xcshareddata/xcschemes/ApplozicSwiftDemoTests.xcscheme
- Demo/Podfile.lock
- Sources/Controllers/ALKConversationListTableViewController.swift
- Sources/Controllers/ALKMediaViewerViewController.swift
- Sources/Controllers/ALKNewChatViewController.swift
- Sources/Views/ALKEmptyView.swift
- Sources/Views/ALKFriendNewChatCell.swift
This fixes the sizing issue, where empty view was not center aligned in some cases.
Also, added missing shared schemes as CI is failing.
> [AL-3875] Update ALKEmptyView to ReusableHeaderFooterView #trivial

- Sources/Controllers/ALKReplyController.swift
Make reply view controller as transparent
Works fine checked with a reply message
> Background color reply controller #trivial

- Sources/ViewModels/ALKConversationViewModel.swift
ChatId was not resetting 
Checked on the device by login at the first time and send some messages to tap on the notification
> Add setter for chatId 

- Sources/Controllers/ALKParticipantSelectionViewContoller.swift
- Sources/Views/StoryBoards/CreateGroupChat.storyboard
Set the white color in add member controller 
Checked with dark mode enable
> Set the defaults color to white for dark mode in add member controller

- ApplozicSwift.podspec
- CHANGELOG.md
- Demo/Podfile.lock
- Sources/Controllers/ALKConversationViewController.swift
> Release 4.0.1

- CHANGELOG.md
- Sources/Controllers/ALKConversationListTableViewController.swift
Fixed leave group and add loading indicator
Tested on the device works fine
> [CM-141] Fix the leave group and add loading indicator

- Sources/Controllers/ALKBaseViewController.swift
- Sources/Controllers/ALKConversationListViewController.swift
- Sources/Controllers/ALKConversationViewController.swift
- Sources/Controllers/ALKSearchResultViewController.swift
- Sources/Utilities/NotificationHelper.swift
Make some functions open and move the code related to the search controller in the same class 
To use it in custom view Controller 
Tested the methods are getting called.
> Make some func open and move the search controller in same class #trivial 

- Sources/Controllers/ALKConversationViewController.swift
Make the public function  so that it can be used in other view controller and move the setup nav bar in view Will appear
Tried with sample app it works fine
> Make some methods public and move setup nav to view will appear#trivial   

- CHANGELOG.md
- Sources/ViewModels/ALKConversationViewModel.swift
* Only load the search messages.
* Fixed reply message fetching.
Tested with search enabled works fine.
> [CM-146] Fix the search messages loading 

- CHANGELOG.md
- RichMessageKit/Extensions/UIView+AutoLayout.swift
- Sources/Controllers/ALKConversationViewController.swift
Fixed the init of the MQTT service object 
I tried sending some messages in some conversation and in a different conversation and clicking on the notification in the simulator.
> [CM-276]Fixed the crash for bad accessing MQTT service obj

- CHANGELOG.md
- Demo/ApplozicSwiftDemo.xcodeproj/project.pbxproj
- Demo/ApplozicSwiftDemo/ALChatManager.swift
- Demo/ApplozicSwiftDemo/AppDelegate.swift
- Demo/ApplozicSwiftDemo/LoginViewController.swift
- Demo/ApplozicSwiftDemoTests/Mocks/ALMessageDBServiceMock.swift
- Sources/Controllers/ALKConversationListViewController.swift
- Sources/Controllers/ALKConversationViewController.swift
- Sources/Controllers/ALKCreateGroupViewController.swift
- Sources/Controllers/ALKCustomCameraViewController.swift
- Sources/Controllers/ALKCustomPickerViewController.swift
- Sources/Utilities/ALKFileUtils.swift
- Sources/Utilities/AVCaptureVideoOrientation+Extension.swift
- Sources/Utilities/Array+Extension.swift
- Sources/ViewModels/ALKConversationListViewModel.swift
- Sources/ViewModels/ALKConversationViewModel.swift
- Sources/ViewModels/SearchResultViewModel.swift
- Sources/Views/ALKPhotoCell.swift
- Sources/Views/ALKVideoCell.swift
- Sources/Views/ALKVoiceCell.swift
- Sources/Views/AudioRecordButton.swift
Migrate to Swift 5 and Fix the warnings
Tested with basic sending message and receiving
> Migrate to swift 5 and Fix the warnings #trivial 

- Sources/Controllers/ALKConversationViewController+TableView.swift
- Sources/Views/ALKFormCell.swift
- Sources/Views/ALKMyFormCell.swift
- Removed empty rows from the table view in the `ALKFormCell`, which were showing up in the bottom.
- Corrected table view and time label constraints in the sender side of the form cell.
- Merging to form-template feature branch.
Form message is correctly rendering on both the sides(sender and receiver). See attached screenshots on [Jira issue](https://applozic.atlassian.net/browse/CM-357)
> Remove empty rows from form view list and correct sender view constraints #trivial

- ApplozicSwift.podspec
- Demo/Podfile.lock
Update applozic pod to 7.8.3
Sending messages and receiving in group
> Update applozic pod to 7.8.3#trivial 

- ApplozicSwift.podspec
- CHANGELOG.md
- Demo/Podfile.lock
Update applozic pod to 7.9.1
Tested the group create and one to one chat
The tested form is displaying r not after going back and coming to the same thread
> Update applozic 7.9.1 #trivial 

- CHANGELOG.md
- Sources/Controllers/ALKConversationViewController+TableView.swift
- Sources/Controllers/ALKConversationViewController.swift
- Sources/Models/FormTemplate.swift
- Sources/Resources/Base.lproj/Localizable.strings
- Sources/Utilities/ALKRegexValidator.swift
- Sources/Utilities/SystemMessage.swift
- Sources/ViewModels/ALKFormViewModelItem.swift
- Sources/Views/ALKFormCell.swift
- Sources/Views/ALKFormTextItemCell.swift
Added the text form validation this on top of CM-402 https://github.com/AppLozic/ApplozicSwift/pull/361 
The form validation will work based on the validation in json for text type and it will have regex and error message to show in the label. 
Once the user clicks on the submit button we will validate and show the error message in case if it's not valid below the text fields.
Form Error label when the email is not valid :
Form when the email is valid :
Tested by sending json from postman for checking form data validation for text type.
JSON : 
`{
"groupId" : "46383008",
"message": "Hi How are you",
"metadata": { "contentType": "300", "templateId": "12", "payload": "[ { \"type\": \"text\", \"data\": { \"label\": \"Name\", \"placeholder\": \"Enter your name\" } }, { \"data\": { …
> [CM-402]Add the support text validation in form template

- CHANGELOG.md
- RichMessageKit/Views/ReceivedButtonsCell.swift
- Sources/Models/ALKChatBarConfiguration.swift
- Sources/Views/ALKChatBar.swift
- Sources/Views/SpeechToTextButton.swift
Added the config in chat bar for text view text and place holder
Tested by changing the color of text view text and place holder text color font.
> [CM-480] Added config for changing textview's text and placeholder style

- CHANGELOG.md
- Demo/ApplozicSwiftDemo/ALChatManager.swift
- Demo/ApplozicSwiftDemo/ContainerViewController.swift
- Demo/ApplozicSwiftDemo/LoginViewController.swift
- Demo/ApplozicSwiftDemo/ViewController.swift
- Sources/Controllers/ALKConversationListViewController.swift
- Sources/Controllers/ALKConversationViewController+Alert.swift
- Sources/Controllers/ALKConversationViewController.swift
- Sources/Controllers/ALKCreateGroupViewController.swift
- Sources/Controllers/ALKCustomCameraPreviewViewController.swift
- Sources/Controllers/ALKCustomCameraViewController.swift
- Sources/Controllers/ALKCustomCropImageViewController.swift
- Sources/Controllers/ALKCustomPickerViewController.swift
- Sources/Controllers/ALKCustomVideoCaptureController.swift
- Sources/Controllers/ALKCustomVideoPreviewViewController.swift
- Sources/Utilities/NotificationHelper.swift
- Sources/Utilities/UIAlertController+Extension.swift
- Sources/Views/ALKDocumentCell.swift
- Sources/Views/ALKFriendMessageCell.swift
Enabled the screen transition animated in all  VC controllers present or dismiss or push
Tested the app works fine after enabling.
> [CM-507] Enable screen transition animations in all screens 

- CHANGELOG.md
- Sources/Controllers/ALKConversationViewController.swift
- Sources/Utilities/Date+Extension.swift
Changed the format of the date-time in a form submission
> Fix for date-time format issue

- CHANGELOG.md
- Demo/ApplozicSwiftDemoUITests/ApplozicSwiftAudioRecordingUITests.swift
- Demo/ApplozicSwiftDemoUITests/ApplozicSwiftGroupSendMessageUITest.swift
- Demo/ApplozicSwiftDemoUITests/ApplozicSwiftMemberUITests.swift
- Demo/Podfile.lock
- Sources/Controllers/ALKConversationListTableViewController.swift
- Sources/Controllers/ALKConversationViewController+TableView.swift
- Sources/Controllers/ALKConversationViewController.swift
- Sources/Controllers/ALKCreateGroupViewController.swift
- Sources/Controllers/ALKCustomCameraViewController.swift
- Sources/Controllers/ALKCustomVideoCaptureController.swift
- Sources/Controllers/ALKParticipantSelectionViewContoller.swift
- Sources/Utilities/ALKUploadTask.swift
- Sources/Utilities/ALKVideoUploadManager.swift
- Sources/ViewModels/ALKConversationViewModel.swift
- Sources/ViewModels/SearchResultViewModel.swift
- Sources/Views/ALKFriendVideoCell.swift
- Sources/Views/ALKVideoCell.swift
Added the support for video thumbnail upload and set the thumbnail for video 
Tested by upload videos and checked the video  thumbnail shows in screen and checked by logout and login and see if the video thumbnail is showing.
> Add the support for video thumbnail

- ApplozicSwift.podspec
- Demo/Podfile.lock
- Package.resolved
- Package.swift
Updated the Kingfisher to 6.3.0 
To fix this issue.
https://github.com/AppLozic/ApplozicSwift/issues/395
as they have fixed it in 5.15.4 
Tested the images are loading fine after updating Kingfisher
> Update Kingfisher to 6.3.0 #trivial 

- Demo/ApplozicSwiftDemo/ALChatManager.swift
- Demo/ApplozicSwiftDemo/AppDelegate.swift
- Demo/ApplozicSwiftDemo/ContainerViewController.swift
- Demo/ApplozicSwiftDemo/PushNotificationHandler.swift
- Demo/ApplozicSwiftDemo/ViewController.swift
Updated the ALChatmanager file for objc methods expose
> Update ALChatManager.swift for objc methods expose #trivial 

- fastlane/Fastfile
Added the allow warnings to true in pod push
> Allow warnings in pod push #trivial 

- RichMessageKit/Utilities/SuggestedReplyViewSizeCalculator.swift
Fix for rich buttons not rendering in multi-line view.
> Fix for rich buttons not rendering in multi-line view

- CHANGELOG.md
- Sources/Views/ALKMessageBaseCell.swift
Fix for firebase crash regarding attributed strings
> [TD-1859] Fix for firebasecrash regarding attributed strings

- RichMessageKit/Utilities/SuggestedReplyViewSizeCalculator.swift
- RichMessageKit/Views/core/SuggestedReplyView.swift
- Sources/Utilities/ALKAppSettingsUserDefaults.swift
- Sources/ViewModels/ALKConversationViewModel.swift
Add support to hide rich message buttons if hidePostCTA settings is enabled.
> Hide rich message buttons

- RichMessageKit/Views/core/SuggestedReplyView.swift
- Sources/Utilities/ALKAppSettingsUserDefaults.swift
Moved the check for hidePostCTA setting to RichMessageKit
> Add check for hidePostCTA settings in RichMessageKit

- ApplozicSwift.podspec
- Demo/Podfile.lock
- Sources/Controllers/ALKConversationListTableViewController.swift
- Sources/Controllers/ALKParticipantSelectionViewContoller.swift
- Sources/Utilities/ALKHTTPManager.swift
- Sources/Utilities/ALKVideoUploadManager.swift
- Sources/ViewModels/ALKConversationListViewModel.swift
- Sources/ViewModels/ALKConversationViewModel.swift
- Sources/ViewModels/ALKNewChatViewModel.swift
- Sources/Views/ALKAttatchmentView.swift
Updated the ApplozicCore to latest version and updated the class methods to instance method
> Update Applozic Core 8.3.0#trivial 

- CHANGELOG.md
- Demo/ApplozicSwiftDemo/ALChatManager.swift
- Demo/ApplozicSwiftDemo/AppDelegate.swift
- RichMessageKit/Utilities/SuggestedReplyViewSizeCalculator.swift
- RichMessageKit/Views/core/SuggestedReplyView.swift
- Sources/Controllers/ALKConversationListViewController.swift
- Sources/Controllers/ALKConversationViewController.swift
- Sources/Controllers/ALKNewChatViewController.swift
- Sources/Controllers/ALKParticipantSelectionViewContoller.swift
- Sources/Views/ListTemplateView.swift
Fixed the MQTT retry issue which was causing an outage on the server by changing the retry policy
> Changed the MQTT retry policy

- Package.resolved
- Package.swift
Updated the Package.swift SPM version of ApplozicCore to 8.3.0
> Update Package.swift for ApplozicCore version to 8.3.0 #trivial 

- Sources/Controllers/ALKConversationListTableViewController.swift
Add support to sync messages on chat screen opening
> [TD-1731] Add support to sync messages on chat screen opening

- Sources/Controllers/ALKConversationViewController.swift
Updated the check for message counts while inserting sections when new messages are added.
> Firebase Crash - updateTableView()
