- Demo/ApplozicSwiftDemo.xcodeproj/project.pbxproj
- Demo/ApplozicSwiftDemoTests/Tests/ALKConversationViewControllerTests.swift
Tests to verify if `addObserver` method gets called when initializing the `ALKConversationViewController` with configuration.
> Add tests to check if observer gets called while initializing

- CHANGELOG.md
- Sources/Controllers/ALKCreateGroupViewController.swift
Fixes an issue which app crashes due to the `configuration`'s value being nil.
> [AL-2885] Fix crash while adding members

- CHANGELOG.md
- Sources/Views/ALKChatBar.swift
This fixes characters going outside message textview boundary while typing long messages
> [AL-2908] Fix message character going out of bounds

- CHANGELOG.md
- Sources/Controllers/ALKConversationListViewController.swift
- Sources/Utilities/SystemMessage.swift
Swipe right on group chat is used to leave group and delete group both. 
This PR will add distinction between the messages when group is swiped right, indicating whether it is to leave group or delete group. 
Also it will fix group disappearing from list when group is left.
> [AL-2932] Fix removal of group from chat list after leaving

- CHANGELOG.md
- Sources/ViewModels/ALKConversationListViewModel.swift
When a new message comes from a user,then all the group messages where this user has sent the last message will get overlapped.
> [Al-2978] Fix overlap of new message with group messages in chatList

- Sources/Views/ALKChatBar.swift
Using `safeAreaLayoutGuide` so that chat bar's bottom padding is correct for the new iPhones.
> [AL-3002]Update chat bar for iPhone X and the new iPhones

- Sources/Controllers/ALKConversationListViewController.swift
- Sources/Controllers/ALKConversationViewController.swift
This PR will add the following checks:
1. When sync call is called, use visible view controller, as conversationViewController can be null. 
2. moveTableViewToBottom shouldn't be called with negative indexPath section. It happened when user is added in the group. And app is opened from notification tap. So number of messages will be 0.
3. unreadScroll button shouldn't come when number of messages is just 1.
> Fix crash when chat opened on tap of notification #trivial

- CHANGELOG.md
- Sources/Controllers/ALKConversationViewController.swift
- Sources/Views/ALKChatBar.swift
Added a header view in `ALKChatBar` which can be used for injecting custom views on top of a chat bar.
By default it's height will be zero and it should be passed from outside.
> [AL-2856]Add a custom header view in chat bar

- Sources/Controllers/ALKConversationListViewController.swift
- Sources/Controllers/ALKConversationViewController.swift
- Sources/Utilities/ALKPushNotificationHandler.swift
- Sources/ViewModels/ALKConversationListViewModel.swift
This fixes an issue which started coming after #104 was merged.
When opening a view controller(`ALKConversationViewController`) by tapping on a notification then `ALKConversationListViewController` will just refresh it.
> [AL-3129]Fix a crash due to pushing same VC multiple times #trivial

- ApplozicSwift.podspec
- CHANGELOG.md
- Demo/Podfile.lock
- Sources/Controllers/ALKConversationListViewController.swift
- Sources/Utilities/ALKPushNotificationHandler.swift
This PR will update notification to include conversationId so that context-based-chat can be displayed correctly after tapping on notification. 
It also updates Applozic dependency to 6.6.1.
> [AL-3131] Update notification to support context-based-chat

- Sources/ViewModels/ALKConversationViewModel.swift
Use channel key first. In case channel key is absent then use contactId.
> Fix loading of earlier messages for group #trivial

- Sources/Controllers/ALKAccountSuspensionController.swift
Changes the access-level of `ALKAccountSuspensionController` to `public`. And added the constraints for the close button.
> [AL-3160] Make ALKAccountSuspensionController public and add constraints #trivial

- CHANGELOG.md
- Sources/Controllers/ALKConversationViewController.swift
- Sources/Models/ALKConfiguration.swift
This PR will do:
1. Allow user to chat for support group even if user is not present in the group. 
2. Fix keyboard show and hide UI in ALKConversationViewController.
3. When loading more messages, table view scroll animation was set to true which was causing noticeable differences in UI so updated the animation to false.
> Enable chat even if user is not in group #trivial

- CHANGELOG.md
- Sources/Controllers/ALKConversationViewController+TableView.swift
- Sources/Controllers/ALKConversationViewController.swift
- Sources/Models/ALKConfiguration.swift
If the config option `disableRichMessageButtonAction`  is true then all the actions on click of rich message buttons like sending a message or opening a URL will be disabled.
> [AL-3196] Add a config option to disable the rich message button clicks

- Sources/Controllers/ALKConversationViewController.swift
This PR will fix an issue where app was crashing because viewModel is nil. Since addObserver is called in init and not viewWillAppear, hence there are chances when viewModel can be nil.
App can crash due to above error.
Hard to reproduce.
> Fix crash due to nil viewmodel in chat screen #trivial

- Demo/ApplozicSwiftDemoTests/Tests/ALKConversationListVCMemoryLeakTests.swift
- Demo/ApplozicSwiftDemoTests/Tests/ALKConversationListViewControllerTests.swift
- Demo/ApplozicSwiftDemoTests/Tests/ALKConversationViewControllerListSnapShotTests.swift
- Sources/Controllers/ALKConversationListTableViewController.swift
- Sources/Controllers/ALKConversationListViewController.swift
- Sources/Utilities/ALKIdentityProtocol.swift
- Sources/Utilities/ConversationListTableViewDataSource.swift
- Sources/Views/ALKChatCell.swift
- This PR will add a way to configure conversation list cell outside the SDK.
- Code will only modify the access specifiers for different views and methods which will be used to configure cell. 
- Example to change cell :: 
> let conversationVC = ALKConversationListViewController(configuration: ALKConfiguration())
conversationVC.conversationListTableViewController.dataSource.cellConfigurator = { (message, tableCell) in
let cell = tableCell as! ALKChatCell
cell.update(viewModel: message, identity: nil)
cell.chatCellDelegate = conversationVC.conversationListTableViewController.self
}
> Add a way to configure chat-cell outside SDK #trivial

- CHANGELOG.md
- Sources/Utilities/Message+Style.swift
- Sources/Views/ALKFriendMessageView.swift
- Sources/Views/ALKFriendPhotoCell.swift
- Sources/Views/ALKMessageCell.swift
- Sources/Views/ALKMyGenericListCell.swift
- Sources/Views/ALKMyMessageView.swift
- Sources/Views/ALKMyPhotoPortalCell.swift
- Sources/Views/ALKPhotoCell.swift
- Added an option to set separate styles for received and sent messages.
- Deprecated `message` style as received and sent message styles have been added.
- Tested by setting a random style. Will add a snapshot test case for this.
> [AL-3257] Add receive and sent message style 📱

- CHANGELOG.md
- Sources/Controllers/ALKConversationViewController.swift
- Sources/Views/ALKConversationNavBar.swift
It will fix an issue where chat details like :: user details on navigation bar, hide/show chat bar etc when conversation is opened from tapping on notification.
Conversation View wasn't being refreshed correctly.
Tested on simulator as well as device.
> Refresh chat details when chat is opened from notification 

- CHANGELOG.md
- Sources/Controllers/ALKConversationListViewController.swift
- Sources/Controllers/ALKConversationViewController.swift
It will fix an issue where typing indicator was coming inside 1-1chat when user was typing in group chat. 
Inconsistent typing indicator behavior
Tested on simulator. Need testing on device.
> [AL-3307] Fix issue where typing comes when user types in other chat

- CHANGELOG.md
- Sources/Controllers/ALKConversationViewController.swift
- Sources/Views/ALKFriendVideoCell.swift
This PR will fix an issue where receiver's profile was not coming in case of video cells.
Tested on simulator, working fine now.
It will also fix the issue where videos recorded from SDK weren't being sent. **The worst kind of bug.** Simply because the delegates were optional and we had an older version of method(I guess) whose signature was slightly different from delegate method(only one parameter) and it wasn't getting called ever.
> [AL-3312] Fix receiver profile issue in video cell

- Sources/Controllers/ALKConversationListViewController.swift
- Sources/Controllers/ALKConversationViewController.swift
- Sources/ViewModels/ALKConversationViewModel.swift
This Pr will add a server call for updating user details whenever 1-1 chat is launched.
This is needed because user connected status is not syncing properly in device.
> Call user detail API whenever detail chat is opened #trivial

- Sources/Views/ALKQuickReplyView.swift
This PR will fix the spacing issue in quick-reply. 
for horizontal stack-view we have spacing of 10. It wasn't added to the width calculation in one of the id condition.
> [AL-3375] Fix spacing problem in quick-reply #trivial

- Sources/Controllers/ALKConversationListViewController.swift
- Sources/Controllers/ALKConversationViewController.swift
- Sources/Views/ALKChatBar.swift
1. This PR will fix an issue which happens in group chat where a user while recording audio when receives a message, placeholder text gets displayed even though audio recording was still in progress. 
2. It also solves another issue where user while recording audio, when removed from group would still be able to send that audio message. After that it works fine.
3. It will solve one more issue where block/unblock wasn't updating chat UI in real-time when performed from other devices.
> [AL-3380] Fix chat-bar UI issue when message comes in group #trivial

- CHANGELOG.md
- Demo/ApplozicSwiftDemo.xcodeproj/project.pbxproj
- Demo/ApplozicSwiftDemo/AppDelegate.swift
- Demo/ApplozicSwiftDemo/ContainerViewController.swift
- Demo/ApplozicSwiftDemo/PushNotificationHandler.swift
- Demo/ApplozicSwiftDemo/ViewController.swift
- Sources/Utilities/NotificationHelper.swift
This PR will add a way to use in-app notifications from outside of SDK. An example of the same is also added in this PR only.
It will allow developers to use a completely different view for in-app notifications and will also solve notification handling issues when our chat controller is added inside containers.
Tested on simulator. Need thorough testing on device.
> [AL-3301] Add a way to use custom views for in-app notifications

- CHANGELOG.md
- Sources/Controllers/ALKConversationViewController.swift
- Sources/Views/ALKChatBar.swift
This will fix an issue where KeyboardWillShow notification observer gets called in `ALKConversationViewController` even though the user is typing somewhere else, for example, when sharing the URL to Slack or Notes app.
Now, if the chatBar's textView is not the first responder then we'll do nothing.
Tested using the 'Share Conversation URL'  feature in Agent app.
> [AL-3486]Add a check for textView when keyboard shows up

- CHANGELOG.md
- Sources/Controllers/ALKConversationViewController.swift
Added support for Back button action in Conversation VC if it was presented not pushed. Now it will dismiss the VC if it can't pop.
Tested in the sample app by changing the default launch button action to present a conversation VC.
> [AL-3490]Add support for Back button action in Conversation VC if presented

- Demo/ApplozicSwiftDemo.xcodeproj/project.pbxproj
- Demo/ApplozicSwiftDemoTests/Tests/TemplateDecoderTests.swift
- Sources/Models/ALKMessageModel.swift
- Sources/Utilities/TemplateDecoder.swift
- Sources/Views/ALKFriendGenericListCell.swift
- Sources/Views/ALKGenericCardCell.swift
- Sources/Views/ALKListTemplateCell.swift
Created a new `TemplateDecoder` type to decode templates instead of doing it manually and in multiple places.
When creating a template model from the metadata, currently we look for the payload in multiple classes, which all those classes are aware of the payload key. The second issue is there is no proper handling in case `payload` is not present in the metadata.
  I handle these two problems by creating a TemplateDecoder which will be responsible for decoding. It will decode to the given template type from the `ALMessage`’s metadata. Throws an error if the `payload` not present. 
Testing: Added unit test cases.
> [AL-3478]Add TemplateDecoder for decoding templates from the metadata #trivial

- CHANGELOG.md
- Sources/Controllers/ALKConversationViewController.swift
- Sources/Views/ALKChatBar.swift
This PR will fix an issue where request for fetching group members was giving nil when done just after inserting a new member in the group.
> [AL-3491] Fix issue where fetchRequest is giving wrong result

- CHANGELOG.md
- Demo/ApplozicSwiftDemoTests/Tests/ALKConversationListViewControllerTests.swift
- Demo/ApplozicSwiftDemoTests/Tests/ALKConversationViewControllerListSnapShotTests.swift
- Demo/ApplozicSwiftDemoTests/Tests/ConversationListTableViewControllerTests.swift
- Sources/Controllers/ALKConversationListTableViewController.swift
- Sources/Controllers/ALKConversationListViewController.swift
- Sources/Controllers/ALKConversationViewController.swift
- Sources/Views/ALKGroupMemberCell.swift
This PR will do the following fixes: 
1. Profile images in group detail page were getting changed while scrolling. 
2. Scrolling tableview to bottom after a delay was causing crash.
3. Fix crash while removing tableview in deinit.
Tested on device.
> [AL-3533] Fix crash while removing tableVC

- CHANGELOG.md
- Sources/Controllers/ALKConversationViewController.swift
- Sources/Views/ALKChatBar+AutoSuggestion.swift
- Sources/Views/ALKChatBar.swift
This will add support for showing autosuggestions. If text input contains a prefix and if that prefix is supported then the suggestions will be shown. And as user types, we'll update the suggestions by showing only those suggestions
whose key contains user-entered text.
Tested it in Agent app where we'll be using this feature and, it's working fine.
> [AL-3391]Add support for autosuggestions

- CHANGELOG.md
- Sources/Controllers/ALKConversationViewController.swift
This PR will disable group title action for support group and open group. 
For normal group, unless the user is part of the group, title action will be disabled.
> Disable group details for support and open group

- Sources/Controllers/ALKConversationViewController.swift
#218 alMqttConversationService was an implicitly unwrapped optional so there might be a possibility of it being nil. 
This PR will add a guard to prevent such mishappenings.
> ConverssationService: remove unwrapped optional #trivial

- Demo/ApplozicSwiftDemo/ALChatManager.swift
Add an exception in case if application id is not passed  and use the default consent from chat manager in case the defaults are cleared
> Use default applicationId consent

- Sources/Controllers/ALKConversationViewController.swift
- Sources/Utilities/ALKActivityIndicator.swift
- Sources/Views/ALKConversationNavBar.swift
This PR will make ALKActivityIndicator public to be used outside and add docs for the usage.
It will make navigation bar of ALKConversationViewController open to be overridden outside.
Required to show user-info screen using overridden ALKConversationViewController.
> Change some APIs to public and open to support user-info-screen

- Sources/Controllers/ALKCreateGroupViewController.swift
In XCode version < 10.2, compiler was giving error "variable viewmodel used before declaration". THis PR will fix this compiler error.
> Fix compiler issue for older XCode #trivial

- CHANGELOG.md
- Demo/ApplozicSwiftDemoTests/Tests/ProfanityFilterTests.swift
- Sources/Controllers/ALKConversationViewController.swift
- Sources/Models/ALKConfiguration.swift
- Sources/Utilities/ProfanityFilter.swift
Added support for passing regular expression pattern to restrict certain messages.
This can be used in combination with the restricted words configuration or individually.
This was required for restricting messages using a pattern. Just comparing words will not cover a lot of different use cases.
Added unit test cases in `ProfanityFilterTests` and, tested in the sample app.
> [AL-3624] Added support for restricting certain messages using regex

- Demo/ApplozicSwiftDemo.xcodeproj/project.pbxproj
- Demo/ApplozicSwiftDemoTests/Tests/NSAttributedStringExtensionTests.swift
- Sources/Controllers/ALKConversationViewController.swift
- Sources/Utilities/NSAttributedString+Extension.swift
Fixed an issue where empty lines in the start and end were part of the message being sent. This was introduced in #260. 
Remove empty lines and white space from the start and end of the message string.
Added unit test cases for the new trim method on `NSAttributedString`. Tried on sample app by sending a message with only spaces, now it won't be sent.
> [AL-3855] Remove empty lines before sending message #trivial

- CHANGELOG.md
- Demo/ApplozicSwiftDemo/AppDelegate.swift
- Sources/Controllers/ALKBaseNavigationController.swift
- Sources/Controllers/ALKBaseViewController.swift
- Sources/Controllers/ALKConversationListViewController.swift
- Sources/Models/ALKConfiguration.swift
This PR will add support for customizing `UINavigationBar` using navigation bar proxy. Now navigation bar properties can be changed from outside using `UIAppearance`. Deprecated navigation bar related configuration properties, but they'll still work for now.
We were hard coding some navigation bar properties which made it difficult to customize. And adding configuration properties for theme changes is not a good idea.
> [AL-3853] Use UIAppearance for navigation bar customization

- CHANGELOG.md
- Sources/Controllers/ALKConversationViewController.swift
- Sources/Utilities/ALKImageView+Extension.swift
- Sources/Utilities/Message+Style.swift
- Sources/Utilities/UIView+Extension.swift
- Sources/Views/ALKFriendContactMessageCell.swift
- Sources/Views/ALKFriendMessageCell.swift
- Sources/Views/ALKFriendVoiceCell.swift
- Sources/Views/ALKMessageBaseCell.swift
- Sources/Views/ALKMyContactMessageCell.swift
- Sources/Views/ALKMyMessageCell.swift
- Sources/Views/ALKMyVoiceCell.swift
- Sources/Views/ALKPhotoCell.swift
- Sources/Views/ContactView.swift
This PR will: 
1. replace popToRootViewController with popViewController when back is pressed in chat screen.
2. Fix force unwrapping of dbMessage
3. add a setting to add border color and border radius to message bubble. It will only work with round message bubbles. 
This setting will be applied to :: 
1. Text Messages
2. Audio Messages
3. Contact Messages. 
This setting won't work on: 
1. Rich messages (Might add support later).
2. Image message.
3. Video messages.
4. Location message.
This is how you can use it:: 
```
ALKMessageStyle.sentBubble.style = .round
ALKMessageStyle.sentBubble.border.color = UIColor.blue
ALKMessageStyle.sentBubble.border.width = 2
ALKMessageStyle.receivedBubble.style = .round
ALKMessageStyle.receivedBubble.border.color = UIColor.red …
```
> [AL-3852] Add setting for message bubble border

- ApplozicSwift.podspec
- Demo/Podfile.lock
- Sources/Controllers/ALKConversationListTableViewController.swift
- Sources/Utilities/UITableView+Extension.swift
Update MGSwipeTableCell for iOS 13 and reload rows once mute or unmute button is tapped.
Even after conversation is muted the swipe button wasn't updating.
> Update MGSwipeTableCell for iOS 13 and update swipe buttons after mute

- Sources/Controllers/ALKNewChatViewController.swift
Fixed an issue where we were pushing `conversationVC` without removing `ALKNewChatViewController` or `ALKCreateGroupViewController` from the stack. Due to which, new chat screen was showing up when you tap on the back button in chat screen.
> Correct the navigation controller stack in new chat #trivial

- Sources/Controllers/ALKConversationListViewController.swift
- Sources/Controllers/ALKSearchResultViewController.swift
- Sources/Utilities/ALKPushNotificationHandler.swift
- Sources/Utilities/NotificationHelper.swift
When search is enabled, then on tapping on notification it will push a new list controller instance. 
Now, on tap of notification chat screen will open directly and on back press, the search controller will be present.
This will also resolve typing indicator issue where typing indicator was coming for wrong conversation after tapping on notification
> Fix push notification issue in search controller #trivial

- Sources/ViewModels/ALKConversationViewModel.swift
- Sources/Views/ALKPhotoCell.swift
- Sources/Views/ALKVideoCell.swift
Earlier in case of contact filepath wasn't updated in the viewmodel so while scrolling it was downloing the contact again
> Update viewmodel with downloaded filepath #trivial

- Sources/Controllers/ALKConversationViewController.swift
- Sources/Models/AutoCompleteItem.swift
- Changed access level of `AutoCompleteManager`'s properties to read the data from outside. 
- Now `autocompleteManager`'s delegate in `ALKConversationViewController` will be set at the creation time, which means the delegate will only be set if the manager is used.
> [AL-3887] AutoComplete: Change access-level and update setup #trivial

- CHANGELOG.md
- Sources/Controllers/ALKConversationViewController.swift
In case of card template, button's `message` property will be used to send a message.
As payload's title is not present, button's name was sent as a message which is not correct.
Tried a card template in the sample app, it's working now.
> [CM-25] CardTemplate: Send a message on button action

- ApplozicSwift.podspec
- CHANGELOG.md
- Demo/Podfile.lock
- Sources/Controllers/ALKAccountSuspensionController.swift
- Sources/Controllers/ALKConversationListViewController.swift
- Sources/Controllers/ALKConversationViewController.swift
Added the method to fetch the package detail and Fixed the close button was not working in case of clicking on any contact to open the chat 
Tested with account closed and re activate
> [CM-135] Call app info API to get the package details after suspension screen is shown

- CHANGELOG.md
- Sources/Controllers/ALKConversationListViewController.swift
- Sources/Controllers/ALKConversationViewController.swift
- Sources/Models/ALKConfiguration.swift
- Sources/Utilities/ALKPushNotificationHandler.swift
Added config for disabling the in-app notification 
Tested using the below config in the app delegate file and notification banner is disabled. Also, tested without config.
```swift
static let config: ALKConfiguration = {
var config = ALKConfiguration()
// Change config based on requirement like:
config.isInAppNotificationBannerDisabled = true
return config
}() 
```
> [CM-168]Added config to disable in app notification banner

- ApplozicSwift.podspec
- Demo/ApplozicSwiftDemo/AppDelegate.swift
- Demo/Podfile.lock
- Sources/Controllers/ALKConversationViewController.swift
* Update Applozic pod to fix the notification click message missing, 
* Remove the ref from app delegate for post notify and change the observer names to default apple name
Notification are triggering for did become active and background
> Update applozic pod to latest #trivial 

- Sources/Controllers/ALKConversationViewController.swift
Added a method to scroll to bottom if last messages are not visible. If you pass a view in chatbar's header, and if the height is updated after message list has been loaded, then some last messages were not visible. In that case this method will be called to scroll down.
And now it's possible to override the ViewModel callbacks like `loadingStarted` and `loadingFinished`. This will be helpful to start other processes once messages are loaded.
It was not possible to scroll down using current methods.
Tested it in KM sample app to show last message on group update notifications.
> [CM-41] Add a method to scroll and allow overriding loading VM callbacks #trivial

- ApplozicSwift.podspec
- Demo/Podfile.lock
Updated `Applozic`, `Nimble` and `SwiftFormat` to their latest versions. Also, updated CocoaPods to 1.9.1.
Updates were required before the release of new version.
All tests are passing.
> Update Applozic, Nimble and SwiftFormat to latest version #trivial

- Sources/Controllers/ALKConversationViewController.swift
Set the priority of context view's top constraint priority to 750. This is required to add a header view on top.  Now we can apply a high priority to another top constrain of context view.
No changes in the current view.
> [CM-199] Lower context view's top constraint priority #trivial

- CHANGELOG.md
- Sources/Controllers/ALKConversationViewController.swift
- Sources/Controllers/ALKCreateGroupViewController.swift
- Sources/Controllers/ALKNewChatViewController.swift
- Sources/Controllers/ALKSearchResultViewController.swift
- Sources/Utilities/ALKHTTPManager.swift
- Sources/ViewModels/ALKConversationViewModel.swift
The group icon was removed due to the passing of an empty string. 
* Tested with changing the group icon 
* Tested with changing the group name 
* Tested by change name and group icon  
All the cases work fine.
> [CM-225] Fixed the group profile was removing when we update group name.

- Sources/Models/ALKChatBarConfiguration.swift
- Sources/Models/ALKConfiguration.swift
- Sources/Views/ALKChatBar.swift
Add config for disable the button tint color for attachments and send message 
Tried with `config.disableButtonTintColor = true` it will disable the tint color and uses the image as we set in config for buttons 
Example: Add the config in the app delegate config object and should take same color which the which is in the image 
```
config.sendMessageIcon = UIImage(named: "send", in: Bundle(for: ALKConversationListViewController.self), compatibleWith: nil)
config.disableButtonTintColor = true
```
> Add config for disable the button tint color #trivial 

- Sources/Utilities/UITextField+Extension.swift
- Sources/Views/ALKFormCell.swift
- Sources/Views/ALKFormMultiSelectItemCell.swift
- Sources/Views/ALKFormPasswordItemCell.swift
- Sources/Views/ALKFormSingleSelectItemCell.swift
- Sources/Views/ALKFormTextItemCell.swift
- Sources/Views/ALKFriendFormCell.swift
- Colors of form item views were changing in the dark mode, so to avoid that I've set the default colors like we do in other views.
- This also contains a fix for submit button visibility issue in the form cell. It was not visible when a new message comes.
Tested in dark mode and by sending form messages when the conversation is open.
> [CM-357] Handle form item colors in dark mode

- CHANGELOG.md
- Sources/Controllers/ALKConversationViewController+TableView.swift
- Sources/Utilities/ALKFormDataCache.swift
- Sources/Views/ALKFormCell.swift
- Sources/Views/ALKFriendFormCell.swift
- Sources/Views/ALKMyFormCell.swift
* Form data text field was not adding the text of the last text field  as the focus of the text field was in the last editing text field
Force the edit text field to end once the submit button clicked.
*Form data cache for submitting data 
Tried in the checking JSON of the submit click and tried with multiple forms and checking if the form data is going for current submit button click
> Add Form data cache and end editing once submit is clicked

- CHANGELOG.md
- Sources/Controllers/ALKConversationViewController.swift
- Fixed a crash that occurred in iOS 13.5 after going back from the group detail or document viewer to a conversation thread.
- We were adding same nav bar items multiple times, and it was crossing the limit.
- Added a check to only add custom nav bar when it's not present.
Tested by launching group detail and document viewer multiple times from the conversation screen.
> [CM-417] Fixed a crash that occurred due to nav bar items limit

- Sources/Controllers/ALKConversationListTableViewController.swift
in iPhone iOS 14 the color background of empty view is cleared
The background color only in iOS 14 it was showing as gray.
Before 
Now: 
Tested by changing the color to match the table view bg color.
> Set the default color in contentView of empty view#trivial 

- CHANGELOG.md
- Sources/Views/ALKBaseCell.swift
Added the  contentView.isUserInteractionEnabled = true in base cell 
When I was working on the date picker I got to know that the form cell is not working any touches in iOS 14 works fine below iOS 14 
Tested with ios 11 or ios 14 checked if the tap button or text fields are working or not in rich messages  works fine now.
> Fix the UserInteraction not working in form cell for iOS 14 only! #trivial 

- CHANGELOG.md
- Sources/Controllers/ALKConversationViewController+TableView.swift
- Sources/Controllers/ALKConversationViewController.swift
- Sources/Controllers/ALKFormDatePickerViewController.swift
- Sources/Controllers/ALKReplyController.swift
- Sources/Models/FormTemplate.swift
- Sources/Resources/Base.lproj/Localizable.strings
- Sources/Utilities/ALKRegexValidator.swift
- Sources/Utilities/Date+Extension.swift
- Sources/Utilities/NotificationHelper.swift
- Sources/Utilities/SystemMessage.swift
- Sources/ViewModels/ALKFormViewModelItem.swift
- Sources/Views/ALKFormCell.swift
- Sources/Views/ALKFormDateItemCell.swift
- Sources/Views/ALKFormTextItemCell.swift
This PR is a date picker implementation only.
Starting Form UI :
iOS 14:
Date:
Date and time.
iOS 13 and below:
Selected values will be updated in form UI  after clicking on the `DONE` button 
Tested with selecting a date , date-time, and time checked in the UI and also in the submit button tap.
> [CM-402] Date picker support in form template

- CHANGELOG.md
- Demo/ApplozicSwiftDemo/ALChatManager.swift
- Sources/Controllers/ALKConversationViewController.swift
- Sources/Utilities/NotificationHelper.swift
- Sources/ViewModels/ALKConversationViewModel.swift
- Sources/Views/ALKChatBar.swift
* This is PR which will be used in KM SDK for adding the support for setting prefilled message before launching the chat and it will be used in the chatbox. 
* Added parameter **prefilledMessage** can be used to pass from Chatmanager.swift file during launching.
Tested with set the prefilled message and launch the chat and see if the text is showing in the chatbox.
> [CM-451] Add the support for passing prefilled message while launching the chat

- Sources/Controllers/ALKConversationViewController.swift
- Sources/Models/CardTemplate.swift
- Sources/Models/ListTemplateModel.swift
This PR will be used in KM SDK  [PR ](https://github.com/Kommunicate-io/Kommunicate-iOS-SDK/pull/136)
* Open the sendQuickReply for overriding in KM SDK for sending language 
Tested in KM by using language bot to check if the  language is changed.
> Make sendQuickReply method open for accessing in KM #trivial

- CHANGELOG.md
- RichMessageKit/Utilities/QuickReplyConfig.swift
- RichMessageKit/Views/SentButtonsCell.swift
- Now, time and message state will be shown in the sender side view of all buttons rich message template.
- Also, used the new message view and corrected message view's left padding.
To match the sender side view to the receiver side.
- By checking the UI of some of the previous messages.
*Before:*
----
*After:*
> [CM-486] Show time, state and correct padding in 'All buttons' rich message template

- CHANGELOG.md
- RichMessageKit/Views/SentButtonsCell.swift
- Sources/Controllers/ALKNewChatViewController.swift
There was an issue when we create a group after clicking on back in chat list screen  navigation bar it was going to add member VC 
checked by group create
> Fix for wrong back stack in nav for group create #trivial 

- CHANGELOG.md
- Demo/ApplozicSwiftDemo/ALChatManager.swift
- Demo/ApplozicSwiftDemoTests/Mocks/ALKConversationViewControllerMock.swift
- Demo/ApplozicSwiftDemoTests/Tests/ALKConversationListVCMemoryLeakTests.swift
- Demo/ApplozicSwiftDemoTests/Tests/ALKConversationListViewControllerTests.swift
- Demo/ApplozicSwiftDemoTests/Tests/ALKConversationVCMemoryLeakTests.swift
- Demo/ApplozicSwiftDemoTests/Tests/ALKConversationViewControllerSnapShotTests.swift
- Demo/ApplozicSwiftDemoTests/Tests/ALKConversationViewControllerTests.swift
- Sources/Controllers/ALKConversationListViewController.swift
- Sources/Controllers/ALKConversationViewController.swift
- Sources/Controllers/ALKCreateGroupViewController.swift
- Sources/Controllers/ALKNewChatViewController.swift
- Sources/Controllers/ALKSearchResultViewController.swift
Fixed the issue where launching chat using methods and keeping the app in the background and clicking on APNS notification the chat was not switching to another conversation if we sent a message from different users or groups.
Made the pushNotification as open can be used in kommunicate to override and handle the refresh this is kommunicate PR which we had fixed the same issue their : https://github.com/Kommunicate-io/Kommunicate-iOS-SDK/pull/108
Will create another PR in kommunicate SDK that will have change for overriding   this `pushNotification` and calling the conversation VC to init with `individual` flag  
There was an issue when we launch the chat using `launchChatWith(contactId: or launchChatWith(clientGroupId:` using `ALChatManager` keeping the app in the background the …
> Fixed the issue conversation switching #trivial 📱 

- CHANGELOG.md
- Sources/Controllers/ALKConversationViewController.swift
- Sources/Views/ALKChatBar.swift
- Used chat bar's attachment color config in the bottom part(safe area) of the chat bar as well.
- Earlier this config option was just used for the attachment part, but there was no way to change the color of the safe area below that. So, used the same color for the safe area.
To change the color of the bottom part of the safe area from outside.
Tested in the default color(gray) and by changing the color like this:
```swift
config.chatBarAttachmentViewBackgroundColor = .cyan
```
Screenshot:
> Apply chat bar attachment color to the bottom part

- CHANGELOG.md
- Sources/Controllers/ALKConversationViewController+TableView.swift
- Sources/Views/ALKFriendFormCell.swift
- Sources/Views/ALKFriendGenericCardMessageCell.swift
- Sources/Views/ALKFriendMessageQuickReplyCell.swift
- Fixed an issue where message part of the quick reply and form template was getting truncated from the bottom.
- Also, removed extra `cell.update(viewModel: message)` call from quick reply cell.
To show full message in templates.
Checked message rendering of different quick reply and form template messages.
> Fix message truncation issue in quick reply and form template

- CHANGELOG.md
- Demo/ApplozicSwiftDemo/ALChatManager.swift
- Sources/Controllers/ALKBaseViewController.swift
Fixed a back button issue where when we launch one to one or group chat screen directly using launch methods the back button was not showing 
* Made the VC to full screen 
Tested by opening the one to one chat directly using launch with userId or groupId
Tested by opening the chat list screen and checked if the back button is showing fine.
Use this methods [link](https://docs.applozic.com/docs/ios-1-1-user-chat-and-group-chat#launching-chat---one-to-one-and-groups-1) for launch the one to one or group chat to check the if the back button shows fine :
> Fixed an back button issue on direct chat launch #trivial 

- CHANGELOG.md
- Sources/Controllers/ALKBaseViewController.swift
Providing `RTL Support` for iOS sdk. Sdk will change layout view's direction if the preferred language belongs RTL.
This feature is already there in Android SDK.Now have been implemented in iOS SDK.
1. Have tested locally in the simulator by changing device language to Arabic.
> [CM-716] RTL Support  in iOS SDK

- CHANGELOG.md
- Sources/Controllers/ALKConversationViewController.swift
- Sources/Models/FormTemplate.swift
This PR for the feature Post submitted form data can also be sent as message based on a flag `postFormDataAsMessage`.
This flag will be there inside the Action object of submit button. For example 
` 
{
"type": "submit",
"data": {
"action": {
"message": "optional- this message will be used as acknowledgement text when user clicks the button",
"requestType": "postBackToBotPlatform",
"postFormDataAsMessage" : "true"
"formAction": "<URL>"
},
"type": "submit",
"name": "Submit"
}
`
Note:
This is already done in Android as well as web sdk.
> [TD-2236] Post Submitted Form Data As Message
